const curatedGames = [
  {
    slug: "place-value-practice",
    title: "Place Value Practice",
    summary:
      "Master multi-digit numbers, decimals, and ordering challenges with adaptive questioning and quick feedback.",
    subject: "Number Sense",
    difficulty: 2,
    estimatedMinutes: 6,
    skills: ["place value", "ordering", "number creation"],
    status: "live",
    loader: () => import("@/components/games/PlaceValuePractice"),
  },
  {
    slug: "stage-1-connected-practice",
    title: "Stage 1 Connected Practice",
    summary:
      "Switch between Stage 1 topics instantly, get helper videos, and build accuracy with focused question generators.",
    subject: "Number Sense",
    difficulty: 2,
    estimatedMinutes: 12,
    skills: [
      "place value",
      "time",
      "negative numbers",
      "powers",
      "fractions",
      "coordinates",
    ],
    status: "live",
    loader: () => import("@/components/games/StageOnePractice"),
  },
  {
    slug: "decimal-sprint",
    title: "Decimal Sprint",
    summary: "Compare, order, and estimate decimals under a light time crunch.",
    subject: "Number Sense",
    difficulty: 3,
    estimatedMinutes: 8,
    skills: ["decimals", "ordering", "estimation"],
    status: "in-design",
  },
  {
    slug: "fraction-lab",
    title: "Fraction Lab",
    summary: "Experiment with fraction models, equivalence, and comparisons through visual tiles.",
    subject: "Fractions",
    difficulty: 3,
    estimatedMinutes: 10,
    skills: ["fractions", "visual models"],
    status: "in-design",
  },
  {
    slug: "geometry-builder",
    title: "Geometry Builder",
    summary: "Construct composite shapes, calculate area, and reason about symmetry.",
    subject: "Geometry",
    difficulty: 4,
    estimatedMinutes: 12,
    skills: ["area", "symmetry", "composition"],
    status: "in-design",
  },
  {
    slug: "ratio-routes",
    title: "Ratio Routes",
    summary: "Scale recipes, maps, and drawings while tracking proportional reasoning accuracy.",
    subject: "Ratios & Rates",
    difficulty: 4,
    estimatedMinutes: 9,
    skills: ["ratios", "unit rates"],
    status: "in-design",
  },
  {
    slug: "data-storyteller",
    title: "Data Storyteller",
    summary: "Interpret mini data sets and explain what changed between related scenarios.",
    subject: "Data",
    difficulty: 2,
    estimatedMinutes: 7,
    skills: ["mean", "median", "data displays"],
    status: "in-design",
  },
];

const TOTAL_GAMES = 100;

const autogeneratedGames = Array.from(
  { length: TOTAL_GAMES - curatedGames.length },
  (_, index) => {
    const id = index + 1;
    return {
      slug: `concept-lab-${id}`,
      title: `Concept Lab ${id}`,
      summary: "Placeholder entry to reserve space for upcoming interactive modules.",
      subject: ["Number Sense", "Fractions", "Geometry", "Data", "Algebra"][
        id % 5
      ],
      difficulty: ((id % 4) + 1),
      estimatedMinutes: 6 + (id % 5),
      skills: ["coming soon"],
      status: "placeholder",
    };
  }
);

export const games = [...curatedGames, ...autogeneratedGames];

export function getGameBySlug(slug) {
  return games.find((game) => game.slug === slug);
}

export function getFeaturedGames() {
  return games.filter((game) => game.status !== "placeholder").slice(0, 6);
}

export function listSubjects() {
  return [...new Set(games.map((game) => game.subject))];
}
